name: Portable Windows Build

on:
  workflow_dispatch:

jobs:
  portable-windows:
    name: "Portable Windows (64-bit)"
    runs-on: windows-latest

    defaults:
      run:
        shell: msys2 {0}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install MSYS2
        uses: msys2/setup-msys2@v2
        with:
          msystem: MINGW64
          update: true
          install: mingw-w64-x86_64-clang mingw-w64-x86_64-cmake mingw-w64-x86_64-autotools mingw-w64-x86_64-tcl git zip

      - name: Build
        run: |
          cd ./Windows
          ./Start.sh
          cmake --build . -j
          cd ..
          strip -s ./bin/multicraft.exe

      - name: Create portable ZIP
        run: |
          mkdir MultiCraft
          cp -r ./bin MultiCraft/
          cp -r ./builtin MultiCraft/
          cp -r ./client MultiCraft/
          cp -r ./fonts MultiCraft/
          cp -r ./locale MultiCraft/
          cp -r ./textures MultiCraft/
          zip -r MultiCraft-portable-windows.zip MultiCraft

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: MultiCraft-portable-windows
          path: ./MultiCraft-portable-windows.zip
